name: ETL Workflow

on:
  push:
    paths:
      - 'Sales_Data.xlsx'

jobs:
  run_etl_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Assicurati di usare la versione di Python che corrisponde al tuo ambiente

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlite3  # Assicurati di includere tutte le librerie necessarie

    - name: Run ETL script
      run: python etl.py
      env:
        MY_ENV_VAR: ${{ secrets.MY_SECRET }}  # Includi qui eventuali variabili d'ambiente o segreti

    - name: Commit and push changes if needed
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add -A
        git commit -m "Automated data update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
